services:
  # calculated-apiのビルダー
  builder:
    image: node:22-alpine
    working_dir: /workspace/calculated-api
    volumes:
      - ./calculated-api:/workspace/calculated-api
      - extensions_vol:/workspace/extensions
    command: sh -c "npm install && npm run sync"
  # Directus本体
  directus:
    image: "directus/directus:11"
    networks:
      - coolify
    ports:
      - "8055:8055"
    restart: unless-stopped
    volumes:
      - ${HOST_UPLOADS_PATH}:/directus/uploads
      - extensions_vol:/directus/extensions
    environment:
      - SECRET
      - DB_CLIENT
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - PUBLIC_URL
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
    depends_on:
      builder:
        condition: service_completed_successfully
volumes:
  extensions_vol:
networks:
  coolify:
    external: true
