services:
  directus:
    build: .
    networks:
      - coolify
    ports:
      - "8055:8055"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${HOST_UPLOADS_PATH}
        target: /directus/uploads
    environment:
      - SECRET
      - DB_CLIENT
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - PUBLIC_URL
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
networks:
  coolify:
    external: true
